### ISSUE TITLE
Error with pandoc

### ISSUE THREAD

**Issue by keiichiiownsu12** [kenkellner/article-epub#1]
Hello,

I was attempting to use your script to download an article from Wiley, however I received this error message:
`RuntimeError: Pandoc died with exitcode "2" during conversion: b'--parse-raw/-R has been removed. Use +raw_html or +raw_tex extension.\n\nTry pandoc --help for more information.\n'
`

I was curious if you knew by any chance a method I could use to debug this? Thank you so much!

Full output:
`Generating epub.............Traceback (most recent call last):`
`  File "/home/ajschadler12/Documents/hi/article-epub-master/article-epub.py", line 45, in <module>
    main()`
`  File "/home/ajschadler12/Documents/hi/article-epub-master/article-epub.py", line 40, in main
    art.epubify(args.o)`
`  File "/home/ajschadler12/Documents/hi/article-epub-master/article_epub/publisher.py", line 165, in epubify`
`    outputfile=output_raw)`
`  File "/home/ajschadler12/.local/lib/python3.6/site-packages/pypandoc/__init__.py", line 103, in convert_text`
`    outputfile=outputfile, filters=filters)`
`  File "/home/ajschadler12/.local/lib/python3.6/site-packages/pypandoc/__init__.py", line 325, in _convert_input`
`    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)`
`RuntimeError: Pandoc died with exitcode "2" during conversion: b'--parse-raw/-R has been removed. Use +raw_html or +raw_tex extension.\n\nTry pandoc --help for more information.\n'`

**Comment by kenkellner** [comment]
Pushed a quick fix, let me know if it doesn't work.
It looks like the Wiley recipe still mostly works, but I haven't been updating things so so some of the other scrapers may be broken. Feel free to submit a pull request if you end up fixing any issues yourself.
