### ISSUE TITLE
Make it compatible with Windows

### ISSUE THREAD

**Issue by kebasaa** [kenkellner/article-epub#2]
Hi, somehow I'm failing to create a pull request, but I have managed to make your code cross-platform (at least adding Windows compatibility). I'm attaching the relevant source file here
[publisher.zip](https://github.com/kenkellner/article-epub/files/4070087/publisher.zip)

**Comment by kenkellner** [comment]
Cool, thanks!. I merged your changes. I haven't used this tool in a while, if you've run into any issues with scraping let me know since I'm sure some publishers are broken.
